apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole and manual
  creationTimestamp: null
  labels:
    app: issuing
  name: issuing
spec:
  containers:
    readinessProbe:
      httpGet:
        path: /api/transaction/3
        port: 5000
      initialDelaySeconds: 10
      timeoutSeconds: 1
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: 6379-tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    deploymentconfig: issuing
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
