apiVersion: v1
data:
  database-password: cmVkaXM=
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  creationTimestamp: null
  labels:
    app: redis-ephemeral
    template: redis-ephemeral-template
  name: redis
type: Opaque
