apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2017-09-28T13:13:06Z
  creationTimestamp: null
  generation: 2
  labels:
    app: issuing
  name: issuing
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: adunicorn/issuing:latest
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/issuing/issuing:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
