apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2017-09-28T13:13:37Z
  creationTimestamp: null
  generation: 2
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: luiscoms/openshift-rabbitmq:3.6.5-management
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/issuing/rabbitmq:3.6.5-management
    generation: 2
    importPolicy: {}
    name: 3.6.5-management
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
